#TODO - figure out how to select the right config to inject into the env
# To run:
# ansible-playbook playbook.yml -u <remote user> -e "consul_addr=<consul host:port> env_prefix=<env tag>"--limit <host to install on>
#
# Note: to run this you need to have docker-py installed on the remote
#       host
---
- hosts: all
  become: True
  become_user: root
  vars_files:
    - vars/devcenterdev.yml

  tasks:

    - name: Copy compose file to server
      copy:
        src: docker-compose.yml
        dest: '/opt/dockerapps/devcenter/docker-compose.yml'
        mode: 0644

    - name: Copy reverse proxy config to server
      copy:
        src: rp.conf
        dest: '/opt/dockerapps/devcenter/rp.conf'
        mode: 0644
    
    - name: Copy atomfeedpub.service config to server
      template: src=atomfeedpub.service dest=/etc/systemd/system/atomfeedpub.service

    - name: Copy nginxproxy.service config to server
      template: src=nginxproxy.service dest=/etc/systemd/system/nginxproxy.service

    - name: Copy syslog.service config to server
      template: src=syslog.service dest=/etc/systemd/system/syslog.service

    - name: Copy logspout.service config to server
      template: src=logspout.service dest=/etc/systemd/system/logspout.service

    - name: Create and start syslog service
      service: state=started name=syslog enabled=yes
      
    - name: Create and start logspout service
      service: state=started name=logspout enabled=yes

    - name: Create and start atomfeedpub service
      service: state=started name=atomfeedpub enabled=yes

    - name: Create and start nginxproxy service
      service: state=started name=nginxproxy enabled=yes


