#TODO - figure out how to select the right config to inject into the env
# To run:
# ansible-playbook playbook.yml -u <remote user> -k -e "user=<user to own certs> " --limit <host to install on>

---
- hosts: all
  become: True
  become_user: root
  vars_files:
    - vars/devcenterdev.yml
  
  tasks:
    - name: Copy env config to server
      template: 
        src: env 
        dest: "/home/{{ user }}/.env"

    - name: Copy compose file to server
      copy:
        src: docker-compose.yml
        dest: '/home/{{ user }}/docker-compose.yml'
        owner: '{{ user }}'
        group: users
        mode: 0644

    - name: Copy reverse proxy config to server
      copy:
        src: rp.conf
        dest: '/home/{{ user }}/rp.conf'
        owner: '{{ user }}'
        group: users
        mode: 0644

